version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    restart: always
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_EMAIL: ${WP_EMAIL}

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      # TODO cambiar por el path del subject
      device: '/d/Proyectos/Cursus/inception/srcs/data/mariadb'
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      # TODO cambiar por el path del subject
      device: '/d/Proyectos/Cursus/inception/srcs/data/wordpress'

networks:
  inception:
    driver: bridge
